# Generated by Django 6.0.7 on 2026-07-29 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='player_class',
            field=models.CharField(choices=[('assassin', 'Assassin'), ('fighter', 'Fighter'), ('mentalist', 'Mentalist'), ('cyborg', 'Cyborg'), ('maniac', 'Maniac'), ('werewolf', 'Werewolf'), ('vampire', 'Vampire')], max_length=20),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('melee', 'Melee'), ('ranged', 'Ranged')], max_length=10)),
                ('damage', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='characters.character')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
