# Generated by Django 6.0.7 on 2026-07-30 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0005_remove_charactermodifier_value_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CharacterAttribute",
        ),
    ]
