# Generated by Django 6.0.7 on 2026-07-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modifiers", "0002_modifiercategory_alter_modifier_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="modifier",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
