# Generated by Django 6.0.7 on 2026-07-30 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_itemattributeeffect"),
        ("modifiers", "0002_modifiercategory_alter_modifier_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="modifiers.modifiercategory",
            ),
        ),
    ]
