# Generated by Django 6.0.7 on 2026-08-01 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0005_alter_item_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="damage",
        ),
        migrations.RemoveField(
            model_name="item",
            name="type",
        ),
    ]
