import type { LucideIcon } from "lucide-react";
import {
  Angry,
  Axe,
  BellRing,
  Bone,
  Brain,
  BrickWall,
  Cable,
  CircleAlert,
  CircleDot,
  CloudDrizzle,
  Compass,
  CornerDownRight,
  DoorOpen,
  Droplets,
  Ear,
  EarOff,
  Eye,
  Feather,
  FileSearch,
  FileX,
  Flame,
  Footprints,
  Ghost,
  Hand,
  Heart,
  House,
  Image,
  KeyRound,
  Leaf,
  Link,
  Map,
  MessageCircle,
  Monitor,
  Moon,
  Music,
  PawPrint,
  Radar,
  Rabbit,
  Radio,
  Route,
  Ruler,
  Scale,
  ScanFace,
  ScanLine,
  Scissors,
  Search,
  ShieldAlert,
  ShieldCheck,
  Snowflake,
  Sparkles,
  Sprout,
  TreePine,
  Unlink,
  Utensils,
  Waves,
  Wind,
} from "lucide-react";

export type ModifierCategory = 1 | 2 | 3 | 4 | 5;

export type ModifierVisual = {
  icon: LucideIcon;
  iconClassName: string;
};

export const modifierCategoryStyles: Record<
  ModifierCategory,
  Pick<ModifierVisual, "iconClassName">
> = {
  1: { iconClassName: "text-sky-400" },
  2: { iconClassName: "text-rose-400" },
  3: { iconClassName: "text-amber-400" },
  4: { iconClassName: "text-emerald-400" },
  5: { iconClassName: "text-violet-400" },
};

function createModifierVisual(
  icon: LucideIcon,
  category: ModifierCategory
): ModifierVisual {
  return {
    icon,
    iconClassName: modifierCategoryStyles[category].iconClassName,
  };
}

/**
 * A chave precisa ser idêntica ao campo `item.modifier.name`
 * retornado pela API.
 */
export const modifierVisualMap: Record<string, ModifierVisual> = {
  // Categoria 1 — Movimento, furtividade e corpo
  "Som de Orvalho": createModifierVisual(CloudDrizzle, 1),
  "Papa-Léguas": createModifierVisual(Rabbit, 1),
  "Cinza de Passo": createModifierVisual(Footprints, 1),
  "Bota Pesada": createModifierVisual(Footprints, 1),
  "Ossos Francos": createModifierVisual(Bone, 1),
  "Sopro Largo": createModifierVisual(Wind, 1),
  "Cirurgião": createModifierVisual(Scissors, 1),
  "Nó Solto": createModifierVisual(Unlink, 1),
  "Pulso de Vidro": createModifierVisual(Hand, 1),
  "Pulso Quebradiço": createModifierVisual(Hand, 1),
  "Laço Curto": createModifierVisual(Cable, 1),
  "Fino Fio": createModifierVisual(Scissors, 1),
  "Espinho de Ferro": createModifierVisual(Cable, 1),
  "Vulto de Concreto": createModifierVisual(BrickWall, 1),
  "Quina Suja": createModifierVisual(CornerDownRight, 1),
  "Pele de Fresta": createModifierVisual(DoorOpen, 1),
  "Sombra Torta": createModifierVisual(Moon, 1),
  "Coluna Reta": createModifierVisual(Ruler, 1),
  "Rosto Quebrado": createModifierVisual(ScanFace, 1),
  "Folha Parada": createModifierVisual(Leaf, 1),
  "Piso Cego": createModifierVisual(Map, 1),
  "Brasa Presa": createModifierVisual(Flame, 1),
  "Sopro Curto": createModifierVisual(Wind, 1),
  "Rota Cega": createModifierVisual(Route, 1),
  "Corda Bamba": createModifierVisual(Scale, 1),
  "Nuca Fria": createModifierVisual(Snowflake, 1),

  // Categoria 2 — Presença, fala e relações sociais
  "Rosto Neutro": createModifierVisual(ScanFace, 2),
  "Asa Pesada": createModifierVisual(Waves, 2),
  "Boca Torturada": createModifierVisual(Angry, 2),
  "Língua de Chuva": createModifierVisual(CloudDrizzle, 2),
  "Fio de Vício": createModifierVisual(Cable, 2),
  "Voz Quebrada": createModifierVisual(MessageCircle, 2),
  "Língua Rígida": createModifierVisual(MessageCircle, 2),
  "Sombra de Dívida": createModifierVisual(Ghost, 2),
  "Mentira de Veludo": createModifierVisual(MessageCircle, 2),
  "Ferro Baixo": createModifierVisual(ShieldAlert, 2),
  "Olho de Ferro": createModifierVisual(Eye, 2),
  "Voz de Barraco": createModifierVisual(MessageCircle, 2),
  "Mão Aberta": createModifierVisual(Hand, 2),
  "Cheiro de Fuga": createModifierVisual(Footprints, 2),
  "Luz Azeda": createModifierVisual(Sparkles, 2),
  "Dente Amargo": createModifierVisual(Bone, 2),
  "Pulso Quente": createModifierVisual(Heart, 2),
  "Fogo Baixo": createModifierVisual(Flame, 2),
  "Voz de Corda": createModifierVisual(Music, 2),
  "Cheiro de Fogão": createModifierVisual(House, 2),

  // Categoria 3 — Sentidos, investigação e alerta
  "Fio de Alarme": createModifierVisual(BellRing, 3),
  "Fio Esticado": createModifierVisual(Radar, 3),
  "Olho Mágico": createModifierVisual(Eye, 3),
  "Orelha Mansa": createModifierVisual(Ear, 3),
  "Orelha Furada": createModifierVisual(EarOff, 3),
  "Ruído Branco": createModifierVisual(Radio, 3),
  "Eco Preso": createModifierVisual(Radio, 3),
  "Eco de Porta": createModifierVisual(KeyRound, 3),
  "Nariz Partido": createModifierVisual(ScanFace, 3),
  "Cheiro de Papel": createModifierVisual(FileSearch, 3),
  "Nariz Morto": createModifierVisual(ScanFace, 3),
  "Linha Invisível": createModifierVisual(Link, 3),
  "Tinta Morta": createModifierVisual(FileX, 3),
  "Fio Solto": createModifierVisual(Unlink, 3),
  "Olho de Estilhaço": createModifierVisual(Eye, 3),
  "Tela Cheia": createModifierVisual(Monitor, 3),
  "Quadro Torto": createModifierVisual(ScanLine, 3),
  "Vista Lavada": createModifierVisual(Eye, 3),
  "Moldura Errada": createModifierVisual(Image, 3),
  "Orelha de Fita": createModifierVisual(Search, 3),
  "Chão Falado": createModifierVisual(Footprints, 3),
  "Círculo Velho": createModifierVisual(CircleDot, 3),
  "Rastro Frio": createModifierVisual(Footprints, 3),
  "Página Rápida": createModifierVisual(FileSearch, 3),

  // Categoria 4 — Resistência, saúde e vulnerabilidade
  "Ossos Ocos": createModifierVisual(Bone, 4),
  "Ossos Justos": createModifierVisual(Bone, 4),
  "Coração Seco": createModifierVisual(Heart, 4),
  "Nervo Solto": createModifierVisual(Brain, 4),
  "Ferrugem Boa": createModifierVisual(ShieldCheck, 4),
  "Carne Surda": createModifierVisual(ShieldCheck, 4),
  "Pele Aberta": createModifierVisual(ShieldAlert, 4),
  "Olho Fendido": createModifierVisual(Eye, 4),
  "Casca Fina": createModifierVisual(ShieldAlert, 4),
  "Estômago de Cinza": createModifierVisual(Utensils, 4),
  "Nó de Fome": createModifierVisual(CircleDot, 4),
  "Estômago Frágil": createModifierVisual(Utensils, 4),
  "Sangue Denso": createModifierVisual(Droplets, 4),
  "Cinza no Pulmão": createModifierVisual(Wind, 4),
  "Sangue Ralo": createModifierVisual(Droplets, 4),
  "Pele de Vidro": createModifierVisual(ShieldAlert, 4),
  "Pele de Horizonte": createModifierVisual(ShieldCheck, 4),
  "Casca Cega": createModifierVisual(Brain, 4),
  "Agulha Torta": createModifierVisual(Scissors, 4),

  // Categoria 5 — Reputação, sobrenatural e território
  "Linha Oculta": createModifierVisual(Map, 5),
  "Traço Errado": createModifierVisual(Compass, 5),
  "Chumbo Leve": createModifierVisual(Scale, 5),
  "Eco Sujo": createModifierVisual(Ghost, 5),
  "Sangue Antigo": createModifierVisual(Droplets, 5),
  "Sussurro Vermelho": createModifierVisual(MessageCircle, 5),
  "Sabor de Ferro": createModifierVisual(Droplets, 5),
  "Raiz Marcada": createModifierVisual(Sprout, 5),
  "Folha Queimada": createModifierVisual(Flame, 5),
  "Galho Raso": createModifierVisual(TreePine, 5),
  "Raiz Cortada": createModifierVisual(Axe, 5),
  "Brilho Torto": createModifierVisual(Sparkles, 5),
  "Pó de Luz": createModifierVisual(Sparkles, 5),
  "Asa Emprestada": createModifierVisual(Feather, 5),
  "Crepúsculo Rachado": createModifierVisual(Moon, 5),
  "Fenda Fria": createModifierVisual(Snowflake, 5),
  "Uivo Fundo": createModifierVisual(PawPrint, 5),
  "Pelo de Rua": createModifierVisual(PawPrint, 5),
  "Pelo Erguido": createModifierVisual(PawPrint, 5),
  "Rosto Quebrado (Reputação)": createModifierVisual(ScanFace, 5),
  "Voz de Barraco (Reputação)": createModifierVisual(
    MessageCircle,
    5
  ),
  "Mapa Rasgado": createModifierVisual(Map, 5),
  "Risco Miúdo": createModifierVisual(Map, 5),
  "Buraco Velho": createModifierVisual(DoorOpen, 5),
  "Buraco Marcado": createModifierVisual(CircleAlert, 5),
  "Véu de Alice": createModifierVisual(Ghost, 5),
  "Sopro de Alice": createModifierVisual(Wind, 5),
};