# Generated by Django 6.0.7 on 2026-07-30 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="action",
            name="created",
        ),
    ]
