# Generated by Django 6.0.7 on 2026-08-02 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_characteraction_result"),
        ("items", "0007_itemtype_item_item_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionItemRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                ("min_quantity", models.PositiveIntegerField(default=1)),
                ("consumed_on_use", models.BooleanField(default=False)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_requirements",
                        to="games.action",
                    ),
                ),
                (
                    "item_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="items.itemtype"
                    ),
                ),
            ],
            options={
                "unique_together": {("action", "item_type")},
            },
        ),
    ]
