# Generated by Django 6.0.7 on 2026-08-03 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0006_delete_characterattribute"),
        ("games", "0005_actionitemrequirement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Act",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "reward_type",
                    models.CharField(
                        choices=[("MO", "Modifier"), ("IT", "Item"), ("BA", "Badge")],
                        max_length=50,
                    ),
                ),
                ("reward_id", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Scene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "act",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.act"
                    ),
                ),
                (
                    "on_fail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failed_from",
                        to="games.scene",
                    ),
                ),
                (
                    "on_hard_fail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hard_failed_from",
                        to="games.scene",
                    ),
                ),
                (
                    "on_success",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="succeeded_from",
                        to="games.scene",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CharacterProgressOnAct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("finished", models.BooleanField(default=False)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="characters.character",
                    ),
                ),
                (
                    "current_scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.scene"
                    ),
                ),
            ],
            options={
                "unique_together": {("character", "current_scene")},
            },
        ),
    ]
