# Generated by Django 6.0.7 on 2026-08-03 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_act_scene_characterprogressonact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scene",
            name="on_fail",
        ),
        migrations.RemoveField(
            model_name="scene",
            name="on_hard_fail",
        ),
        migrations.RemoveField(
            model_name="scene",
            name="on_success",
        ),
        migrations.AlterField(
            model_name="act",
            name="reward_type",
            field=models.CharField(
                choices=[("MO", "Modifier"), ("IT", "Item"), ("BA", "Badge")],
                default="MO",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="SceneAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[("P", "Player"), ("H", "History")],
                        default="H",
                        max_length=1,
                    ),
                ),
                (
                    "history_action",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="games.action",
                    ),
                ),
                (
                    "on_fail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failed_from",
                        to="games.scene",
                    ),
                ),
                (
                    "on_hard_fail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hard_failed_from",
                        to="games.scene",
                    ),
                ),
                (
                    "on_success",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="succeeded_from",
                        to="games.scene",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.scene"
                    ),
                ),
            ],
        ),
    ]
