# Generated by Django 6.0.7 on 2026-08-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0007_remove_scene_on_fail_remove_scene_on_hard_fail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scene",
            name="initial",
            field=models.BooleanField(default=False),
        ),
    ]
