# Generated by Django 6.0.7 on 2026-08-03 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0006_delete_characterattribute"),
        ("games", "0008_scene_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scene",
            options={"ordering": ["order"]},
        ),
        migrations.AlterUniqueTogether(
            name="characterprogressonact",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="characterprogressonact",
            name="act",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progresses_on_act",
                to="games.act",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scene",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="characterprogressonact",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progresses",
                to="characters.character",
            ),
        ),
        migrations.AlterField(
            model_name="characterprogressonact",
            name="current_scene",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_progresses",
                to="games.scene",
            ),
        ),
        migrations.AlterField(
            model_name="scene",
            name="act",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scenes",
                to="games.act",
            ),
        ),
        migrations.AlterField(
            model_name="sceneaction",
            name="scene",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scene_actions",
                to="games.scene",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="characterprogressonact",
            unique_together={("character", "act")},
        ),
    ]
